//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace mamSearchAndRetrieval.org.ngs.ipmam.um {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UMSoap", Namespace="http://www.blue-order.com/ma/usermanagementws/um")]
    public partial class UM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginExOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginAsMandateOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginAsMandateExOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefreshSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsRightGrantedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPropertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSessionInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPropertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePropertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserTenantsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloneSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloneSessionExOperationCompleted;
        
        private System.Threading.SendOrPostCallback SwitchTenantOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UM() {
            this.Url = global::mamSearchAndRetrieval.Properties.Settings.Default.mamSearchAndRetrieval_org_ngs_ipmam_um_UM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LoginExCompletedEventHandler LoginExCompleted;
        
        /// <remarks/>
        public event LoginAsMandateCompletedEventHandler LoginAsMandateCompleted;
        
        /// <remarks/>
        public event LoginAsMandateExCompletedEventHandler LoginAsMandateExCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event RefreshSessionCompletedEventHandler RefreshSessionCompleted;
        
        /// <remarks/>
        public event IsRightGrantedCompletedEventHandler IsRightGrantedCompleted;
        
        /// <remarks/>
        public event GetRightsCompletedEventHandler GetRightsCompleted;
        
        /// <remarks/>
        public event GetUserPropertiesCompletedEventHandler GetUserPropertiesCompleted;
        
        /// <remarks/>
        public event GetUserPropertyCompletedEventHandler GetUserPropertyCompleted;
        
        /// <remarks/>
        public event GetUserGroupsCompletedEventHandler GetUserGroupsCompleted;
        
        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
        
        /// <remarks/>
        public event GetSessionInfoCompletedEventHandler GetSessionInfoCompleted;
        
        /// <remarks/>
        public event SetPasswordCompletedEventHandler SetPasswordCompleted;
        
        /// <remarks/>
        public event SetPropertiesCompletedEventHandler SetPropertiesCompleted;
        
        /// <remarks/>
        public event SetPropertyCompletedEventHandler SetPropertyCompleted;
        
        /// <remarks/>
        public event DeletePropertyCompletedEventHandler DeletePropertyCompleted;
        
        /// <remarks/>
        public event GetUserTenantsCompletedEventHandler GetUserTenantsCompleted;
        
        /// <remarks/>
        public event CloneSessionCompletedEventHandler CloneSessionCompleted;
        
        /// <remarks/>
        public event CloneSessionExCompletedEventHandler CloneSessionExCompleted;
        
        /// <remarks/>
        public event SwitchTenantCompletedEventHandler SwitchTenantCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/Login", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string user, string pwd) {
            object[] results = this.Invoke("Login", new object[] {
                        user,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string user, string pwd) {
            this.LoginAsync(user, pwd, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string user, string pwd, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        user,
                        pwd}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/LoginEx", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginEx(string user, string pwd, string tenant) {
            object[] results = this.Invoke("LoginEx", new object[] {
                        user,
                        pwd,
                        tenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginExAsync(string user, string pwd, string tenant) {
            this.LoginExAsync(user, pwd, tenant, null);
        }
        
        /// <remarks/>
        public void LoginExAsync(string user, string pwd, string tenant, object userState) {
            if ((this.LoginExOperationCompleted == null)) {
                this.LoginExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginExOperationCompleted);
            }
            this.InvokeAsync("LoginEx", new object[] {
                        user,
                        pwd,
                        tenant}, this.LoginExOperationCompleted, userState);
        }
        
        private void OnLoginExOperationCompleted(object arg) {
            if ((this.LoginExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginExCompleted(this, new LoginExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/LoginAsMandate", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginAsMandate(string accesstoken, string user) {
            object[] results = this.Invoke("LoginAsMandate", new object[] {
                        accesstoken,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsMandateAsync(string accesstoken, string user) {
            this.LoginAsMandateAsync(accesstoken, user, null);
        }
        
        /// <remarks/>
        public void LoginAsMandateAsync(string accesstoken, string user, object userState) {
            if ((this.LoginAsMandateOperationCompleted == null)) {
                this.LoginAsMandateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAsMandateOperationCompleted);
            }
            this.InvokeAsync("LoginAsMandate", new object[] {
                        accesstoken,
                        user}, this.LoginAsMandateOperationCompleted, userState);
        }
        
        private void OnLoginAsMandateOperationCompleted(object arg) {
            if ((this.LoginAsMandateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAsMandateCompleted(this, new LoginAsMandateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/LoginAsMandateEx", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginAsMandateEx(string accesstoken, string user, string tenant) {
            object[] results = this.Invoke("LoginAsMandateEx", new object[] {
                        accesstoken,
                        user,
                        tenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsMandateExAsync(string accesstoken, string user, string tenant) {
            this.LoginAsMandateExAsync(accesstoken, user, tenant, null);
        }
        
        /// <remarks/>
        public void LoginAsMandateExAsync(string accesstoken, string user, string tenant, object userState) {
            if ((this.LoginAsMandateExOperationCompleted == null)) {
                this.LoginAsMandateExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAsMandateExOperationCompleted);
            }
            this.InvokeAsync("LoginAsMandateEx", new object[] {
                        accesstoken,
                        user,
                        tenant}, this.LoginAsMandateExOperationCompleted, userState);
        }
        
        private void OnLoginAsMandateExOperationCompleted(object arg) {
            if ((this.LoginAsMandateExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAsMandateExCompleted(this, new LoginAsMandateExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/Logout", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout(string accesstoken) {
            this.Invoke("Logout", new object[] {
                        accesstoken});
        }
        
        /// <remarks/>
        public void LogoutAsync(string accesstoken) {
            this.LogoutAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(string accesstoken, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        accesstoken}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/RefreshSession", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RefreshSession(string accesstoken) {
            this.Invoke("RefreshSession", new object[] {
                        accesstoken});
        }
        
        /// <remarks/>
        public void RefreshSessionAsync(string accesstoken) {
            this.RefreshSessionAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void RefreshSessionAsync(string accesstoken, object userState) {
            if ((this.RefreshSessionOperationCompleted == null)) {
                this.RefreshSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefreshSessionOperationCompleted);
            }
            this.InvokeAsync("RefreshSession", new object[] {
                        accesstoken}, this.RefreshSessionOperationCompleted, userState);
        }
        
        private void OnRefreshSessionOperationCompleted(object arg) {
            if ((this.RefreshSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefreshSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/IsRightGranted", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsRightGranted(string accesstoken, string right) {
            object[] results = this.Invoke("IsRightGranted", new object[] {
                        accesstoken,
                        right});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsRightGrantedAsync(string accesstoken, string right) {
            this.IsRightGrantedAsync(accesstoken, right, null);
        }
        
        /// <remarks/>
        public void IsRightGrantedAsync(string accesstoken, string right, object userState) {
            if ((this.IsRightGrantedOperationCompleted == null)) {
                this.IsRightGrantedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsRightGrantedOperationCompleted);
            }
            this.InvokeAsync("IsRightGranted", new object[] {
                        accesstoken,
                        right}, this.IsRightGrantedOperationCompleted, userState);
        }
        
        private void OnIsRightGrantedOperationCompleted(object arg) {
            if ((this.IsRightGrantedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsRightGrantedCompleted(this, new IsRightGrantedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetRights", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetRights(string accesstoken, string category) {
            object[] results = this.Invoke("GetRights", new object[] {
                        accesstoken,
                        category});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRightsAsync(string accesstoken, string category) {
            this.GetRightsAsync(accesstoken, category, null);
        }
        
        /// <remarks/>
        public void GetRightsAsync(string accesstoken, string category, object userState) {
            if ((this.GetRightsOperationCompleted == null)) {
                this.GetRightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRightsOperationCompleted);
            }
            this.InvokeAsync("GetRights", new object[] {
                        accesstoken,
                        category}, this.GetRightsOperationCompleted, userState);
        }
        
        private void OnGetRightsOperationCompleted(object arg) {
            if ((this.GetRightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRightsCompleted(this, new GetRightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetUserProperties", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Property[] GetUserProperties(string accesstoken) {
            object[] results = this.Invoke("GetUserProperties", new object[] {
                        accesstoken});
            return ((Property[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPropertiesAsync(string accesstoken) {
            this.GetUserPropertiesAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void GetUserPropertiesAsync(string accesstoken, object userState) {
            if ((this.GetUserPropertiesOperationCompleted == null)) {
                this.GetUserPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPropertiesOperationCompleted);
            }
            this.InvokeAsync("GetUserProperties", new object[] {
                        accesstoken}, this.GetUserPropertiesOperationCompleted, userState);
        }
        
        private void OnGetUserPropertiesOperationCompleted(object arg) {
            if ((this.GetUserPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPropertiesCompleted(this, new GetUserPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetUserProperty", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserProperty(string accesstoken, string property) {
            object[] results = this.Invoke("GetUserProperty", new object[] {
                        accesstoken,
                        property});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPropertyAsync(string accesstoken, string property) {
            this.GetUserPropertyAsync(accesstoken, property, null);
        }
        
        /// <remarks/>
        public void GetUserPropertyAsync(string accesstoken, string property, object userState) {
            if ((this.GetUserPropertyOperationCompleted == null)) {
                this.GetUserPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPropertyOperationCompleted);
            }
            this.InvokeAsync("GetUserProperty", new object[] {
                        accesstoken,
                        property}, this.GetUserPropertyOperationCompleted, userState);
        }
        
        private void OnGetUserPropertyOperationCompleted(object arg) {
            if ((this.GetUserPropertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPropertyCompleted(this, new GetUserPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetUserGroups", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetUserGroups(string accesstoken) {
            object[] results = this.Invoke("GetUserGroups", new object[] {
                        accesstoken});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserGroupsAsync(string accesstoken) {
            this.GetUserGroupsAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void GetUserGroupsAsync(string accesstoken, object userState) {
            if ((this.GetUserGroupsOperationCompleted == null)) {
                this.GetUserGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserGroupsOperationCompleted);
            }
            this.InvokeAsync("GetUserGroups", new object[] {
                        accesstoken}, this.GetUserGroupsOperationCompleted, userState);
        }
        
        private void OnGetUserGroupsOperationCompleted(object arg) {
            if ((this.GetUserGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserGroupsCompleted(this, new GetUserGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetUserInfo", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInformation GetUserInfo(string accesstoken) {
            object[] results = this.Invoke("GetUserInfo", new object[] {
                        accesstoken});
            return ((UserInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string accesstoken) {
            this.GetUserInfoAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string accesstoken, object userState) {
            if ((this.GetUserInfoOperationCompleted == null)) {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[] {
                        accesstoken}, this.GetUserInfoOperationCompleted, userState);
        }
        
        private void OnGetUserInfoOperationCompleted(object arg) {
            if ((this.GetUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetSessionInfo", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SessionInformation GetSessionInfo(string accesstoken) {
            object[] results = this.Invoke("GetSessionInfo", new object[] {
                        accesstoken});
            return ((SessionInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetSessionInfoAsync(string accesstoken) {
            this.GetSessionInfoAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void GetSessionInfoAsync(string accesstoken, object userState) {
            if ((this.GetSessionInfoOperationCompleted == null)) {
                this.GetSessionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSessionInfoOperationCompleted);
            }
            this.InvokeAsync("GetSessionInfo", new object[] {
                        accesstoken}, this.GetSessionInfoOperationCompleted, userState);
        }
        
        private void OnGetSessionInfoOperationCompleted(object arg) {
            if ((this.GetSessionInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSessionInfoCompleted(this, new GetSessionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/SetPassword", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetPassword(string accesstoken, string passwd) {
            this.Invoke("SetPassword", new object[] {
                        accesstoken,
                        passwd});
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string accesstoken, string passwd) {
            this.SetPasswordAsync(accesstoken, passwd, null);
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string accesstoken, string passwd, object userState) {
            if ((this.SetPasswordOperationCompleted == null)) {
                this.SetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPasswordOperationCompleted);
            }
            this.InvokeAsync("SetPassword", new object[] {
                        accesstoken,
                        passwd}, this.SetPasswordOperationCompleted, userState);
        }
        
        private void OnSetPasswordOperationCompleted(object arg) {
            if ((this.SetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/SetProperties", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetProperties(string accesstoken, Property[] properties) {
            this.Invoke("SetProperties", new object[] {
                        accesstoken,
                        properties});
        }
        
        /// <remarks/>
        public void SetPropertiesAsync(string accesstoken, Property[] properties) {
            this.SetPropertiesAsync(accesstoken, properties, null);
        }
        
        /// <remarks/>
        public void SetPropertiesAsync(string accesstoken, Property[] properties, object userState) {
            if ((this.SetPropertiesOperationCompleted == null)) {
                this.SetPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPropertiesOperationCompleted);
            }
            this.InvokeAsync("SetProperties", new object[] {
                        accesstoken,
                        properties}, this.SetPropertiesOperationCompleted, userState);
        }
        
        private void OnSetPropertiesOperationCompleted(object arg) {
            if ((this.SetPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPropertiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/SetProperty", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetProperty(string accesstoken, string propertyname, string propertyvalue) {
            this.Invoke("SetProperty", new object[] {
                        accesstoken,
                        propertyname,
                        propertyvalue});
        }
        
        /// <remarks/>
        public void SetPropertyAsync(string accesstoken, string propertyname, string propertyvalue) {
            this.SetPropertyAsync(accesstoken, propertyname, propertyvalue, null);
        }
        
        /// <remarks/>
        public void SetPropertyAsync(string accesstoken, string propertyname, string propertyvalue, object userState) {
            if ((this.SetPropertyOperationCompleted == null)) {
                this.SetPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPropertyOperationCompleted);
            }
            this.InvokeAsync("SetProperty", new object[] {
                        accesstoken,
                        propertyname,
                        propertyvalue}, this.SetPropertyOperationCompleted, userState);
        }
        
        private void OnSetPropertyOperationCompleted(object arg) {
            if ((this.SetPropertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPropertyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/DeleteProperty", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteProperty(string accesstoken, string property) {
            this.Invoke("DeleteProperty", new object[] {
                        accesstoken,
                        property});
        }
        
        /// <remarks/>
        public void DeletePropertyAsync(string accesstoken, string property) {
            this.DeletePropertyAsync(accesstoken, property, null);
        }
        
        /// <remarks/>
        public void DeletePropertyAsync(string accesstoken, string property, object userState) {
            if ((this.DeletePropertyOperationCompleted == null)) {
                this.DeletePropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePropertyOperationCompleted);
            }
            this.InvokeAsync("DeleteProperty", new object[] {
                        accesstoken,
                        property}, this.DeletePropertyOperationCompleted, userState);
        }
        
        private void OnDeletePropertyOperationCompleted(object arg) {
            if ((this.DeletePropertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePropertyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/GetUserTenants", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TenantInformation[] GetUserTenants(string accesstoken) {
            object[] results = this.Invoke("GetUserTenants", new object[] {
                        accesstoken});
            return ((TenantInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserTenantsAsync(string accesstoken) {
            this.GetUserTenantsAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void GetUserTenantsAsync(string accesstoken, object userState) {
            if ((this.GetUserTenantsOperationCompleted == null)) {
                this.GetUserTenantsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserTenantsOperationCompleted);
            }
            this.InvokeAsync("GetUserTenants", new object[] {
                        accesstoken}, this.GetUserTenantsOperationCompleted, userState);
        }
        
        private void OnGetUserTenantsOperationCompleted(object arg) {
            if ((this.GetUserTenantsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserTenantsCompleted(this, new GetUserTenantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/CloneSession", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CloneSession(string accesstoken) {
            object[] results = this.Invoke("CloneSession", new object[] {
                        accesstoken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CloneSessionAsync(string accesstoken) {
            this.CloneSessionAsync(accesstoken, null);
        }
        
        /// <remarks/>
        public void CloneSessionAsync(string accesstoken, object userState) {
            if ((this.CloneSessionOperationCompleted == null)) {
                this.CloneSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloneSessionOperationCompleted);
            }
            this.InvokeAsync("CloneSession", new object[] {
                        accesstoken}, this.CloneSessionOperationCompleted, userState);
        }
        
        private void OnCloneSessionOperationCompleted(object arg) {
            if ((this.CloneSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloneSessionCompleted(this, new CloneSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/CloneSessionEx", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CloneSessionEx(string accesstoken, string tenant) {
            object[] results = this.Invoke("CloneSessionEx", new object[] {
                        accesstoken,
                        tenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CloneSessionExAsync(string accesstoken, string tenant) {
            this.CloneSessionExAsync(accesstoken, tenant, null);
        }
        
        /// <remarks/>
        public void CloneSessionExAsync(string accesstoken, string tenant, object userState) {
            if ((this.CloneSessionExOperationCompleted == null)) {
                this.CloneSessionExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloneSessionExOperationCompleted);
            }
            this.InvokeAsync("CloneSessionEx", new object[] {
                        accesstoken,
                        tenant}, this.CloneSessionExOperationCompleted, userState);
        }
        
        private void OnCloneSessionExOperationCompleted(object arg) {
            if ((this.CloneSessionExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloneSessionExCompleted(this, new CloneSessionExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/usermanagementws/um/SwitchTenant", RequestNamespace="http://www.blue-order.com/ma/usermanagementws/um", ResponseNamespace="http://www.blue-order.com/ma/usermanagementws/um", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SwitchTenant(string accesstoken, string tenant) {
            object[] results = this.Invoke("SwitchTenant", new object[] {
                        accesstoken,
                        tenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SwitchTenantAsync(string accesstoken, string tenant) {
            this.SwitchTenantAsync(accesstoken, tenant, null);
        }
        
        /// <remarks/>
        public void SwitchTenantAsync(string accesstoken, string tenant, object userState) {
            if ((this.SwitchTenantOperationCompleted == null)) {
                this.SwitchTenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSwitchTenantOperationCompleted);
            }
            this.InvokeAsync("SwitchTenant", new object[] {
                        accesstoken,
                        tenant}, this.SwitchTenantOperationCompleted, userState);
        }
        
        private void OnSwitchTenantOperationCompleted(object arg) {
            if ((this.SwitchTenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SwitchTenantCompleted(this, new SwitchTenantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/usermanagementws/um")]
    public partial class Property {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/usermanagementws/um")]
    public partial class TenantInformation {
        
        private string idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private Property[] propertiesField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Property[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/usermanagementws/um")]
    public partial class ItemInfo {
        
        private string idField;
        
        private string displayNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/usermanagementws/um")]
    public partial class SessionInformation {
        
        private string idField;
        
        private ItemInfo userField;
        
        private ItemInfo tenantField;
        
        private ItemInfo[] groupsField;
        
        private ItemInfo[] rightsField;
        
        private Property[] propertiesField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public ItemInfo User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public ItemInfo Tenant {
            get {
                return this.tenantField;
            }
            set {
                this.tenantField = value;
            }
        }
        
        /// <remarks/>
        public ItemInfo[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public ItemInfo[] Rights {
            get {
                return this.rightsField;
            }
            set {
                this.rightsField = value;
            }
        }
        
        /// <remarks/>
        public Property[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/usermanagementws/um")]
    public partial class UserInformation {
        
        private string tokenField;
        
        private string nameField;
        
        private string tenantField;
        
        private string[] groupsField;
        
        private string[] rightsField;
        
        private Property[] propertiesField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string tenant {
            get {
                return this.tenantField;
            }
            set {
                this.tenantField = value;
            }
        }
        
        /// <remarks/>
        public string[] groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public string[] rights {
            get {
                return this.rightsField;
            }
            set {
                this.rightsField = value;
            }
        }
        
        /// <remarks/>
        public Property[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginExCompletedEventHandler(object sender, LoginExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginAsMandateCompletedEventHandler(object sender, LoginAsMandateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAsMandateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAsMandateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginAsMandateExCompletedEventHandler(object sender, LoginAsMandateExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAsMandateExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAsMandateExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RefreshSessionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IsRightGrantedCompletedEventHandler(object sender, IsRightGrantedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsRightGrantedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsRightGrantedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRightsCompletedEventHandler(object sender, GetRightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserPropertiesCompletedEventHandler(object sender, GetUserPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Property[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Property[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserPropertyCompletedEventHandler(object sender, GetUserPropertyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserGroupsCompletedEventHandler(object sender, GetUserGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSessionInfoCompletedEventHandler(object sender, GetSessionInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSessionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSessionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SessionInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SessionInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetPasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetPropertiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetPropertyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeletePropertyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserTenantsCompletedEventHandler(object sender, GetUserTenantsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserTenantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserTenantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenantInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenantInformation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CloneSessionCompletedEventHandler(object sender, CloneSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloneSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloneSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CloneSessionExCompletedEventHandler(object sender, CloneSessionExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloneSessionExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloneSessionExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SwitchTenantCompletedEventHandler(object sender, SwitchTenantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwitchTenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SwitchTenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591