//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace mamSearchAndRetrieval.org.ngs.ipmam.dmLegalListEx2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DMLegalListEx2Soap", Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class DMLegalListEx2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetFixForPlatformOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllLegalListsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMLegalListAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMLegalListLocalizedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMLegalListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUseSymbolsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDefaultIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetLabelOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveEntryForTenantOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetShortcutOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetIconOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback LastModificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomIndicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCustomIndicesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DMLegalListEx2() {
            this.Url = global::mamSearchAndRetrieval.Properties.Settings.Default.mamSearchAndRetrieval_org_ngs_admin_dmLegalListEx2_DMLegalListEx2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetFixForPlatformCompletedEventHandler SetFixForPlatformCompleted;
        
        /// <remarks/>
        public event GetAllLegalListsCompletedEventHandler GetAllLegalListsCompleted;
        
        /// <remarks/>
        public event GetDMLegalListAdminCompletedEventHandler GetDMLegalListAdminCompleted;
        
        /// <remarks/>
        public event GetDMLegalListLocalizedCompletedEventHandler GetDMLegalListLocalizedCompleted;
        
        /// <remarks/>
        public event GetDMLegalListCompletedEventHandler GetDMLegalListCompleted;
        
        /// <remarks/>
        public event SetUseSymbolsCompletedEventHandler SetUseSymbolsCompleted;
        
        /// <remarks/>
        public event SetDefaultIDCompletedEventHandler SetDefaultIDCompleted;
        
        /// <remarks/>
        public event SetLabelCompletedEventHandler SetLabelCompleted;
        
        /// <remarks/>
        public event RemoveEntryForTenantCompletedEventHandler RemoveEntryForTenantCompleted;
        
        /// <remarks/>
        public event SetShortcutCompletedEventHandler SetShortcutCompleted;
        
        /// <remarks/>
        public event SetIconCompletedEventHandler SetIconCompleted;
        
        /// <remarks/>
        public event AddEntryCompletedEventHandler AddEntryCompleted;
        
        /// <remarks/>
        public event RemoveEntryCompletedEventHandler RemoveEntryCompleted;
        
        /// <remarks/>
        public event LastModificationCompletedEventHandler LastModificationCompleted;
        
        /// <remarks/>
        public event GetCustomIndicesCompletedEventHandler GetCustomIndicesCompleted;
        
        /// <remarks/>
        public event SetCustomIndicesCompletedEventHandler SetCustomIndicesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetFixForPlatform", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetFixForPlatform(string accesskey, string legalListName, bool FIX_FOR_PLATFORM) {
            this.Invoke("SetFixForPlatform", new object[] {
                        accesskey,
                        legalListName,
                        FIX_FOR_PLATFORM});
        }
        
        /// <remarks/>
        public void SetFixForPlatformAsync(string accesskey, string legalListName, bool FIX_FOR_PLATFORM) {
            this.SetFixForPlatformAsync(accesskey, legalListName, FIX_FOR_PLATFORM, null);
        }
        
        /// <remarks/>
        public void SetFixForPlatformAsync(string accesskey, string legalListName, bool FIX_FOR_PLATFORM, object userState) {
            if ((this.SetFixForPlatformOperationCompleted == null)) {
                this.SetFixForPlatformOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetFixForPlatformOperationCompleted);
            }
            this.InvokeAsync("SetFixForPlatform", new object[] {
                        accesskey,
                        legalListName,
                        FIX_FOR_PLATFORM}, this.SetFixForPlatformOperationCompleted, userState);
        }
        
        private void OnSetFixForPlatformOperationCompleted(object arg) {
            if ((this.SetFixForPlatformCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetFixForPlatformCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/GetAllLegalLists", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LegalListAdmin[] GetAllLegalLists(string accesskey) {
            object[] results = this.Invoke("GetAllLegalLists", new object[] {
                        accesskey});
            return ((LegalListAdmin[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllLegalListsAsync(string accesskey) {
            this.GetAllLegalListsAsync(accesskey, null);
        }
        
        /// <remarks/>
        public void GetAllLegalListsAsync(string accesskey, object userState) {
            if ((this.GetAllLegalListsOperationCompleted == null)) {
                this.GetAllLegalListsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllLegalListsOperationCompleted);
            }
            this.InvokeAsync("GetAllLegalLists", new object[] {
                        accesskey}, this.GetAllLegalListsOperationCompleted, userState);
        }
        
        private void OnGetAllLegalListsOperationCompleted(object arg) {
            if ((this.GetAllLegalListsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllLegalListsCompleted(this, new GetAllLegalListsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/GetDMLegalListAdmin", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LegalListAdmin GetDMLegalListAdmin(string accesskey, string legalListName) {
            object[] results = this.Invoke("GetDMLegalListAdmin", new object[] {
                        accesskey,
                        legalListName});
            return ((LegalListAdmin)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMLegalListAdminAsync(string accesskey, string legalListName) {
            this.GetDMLegalListAdminAsync(accesskey, legalListName, null);
        }
        
        /// <remarks/>
        public void GetDMLegalListAdminAsync(string accesskey, string legalListName, object userState) {
            if ((this.GetDMLegalListAdminOperationCompleted == null)) {
                this.GetDMLegalListAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMLegalListAdminOperationCompleted);
            }
            this.InvokeAsync("GetDMLegalListAdmin", new object[] {
                        accesskey,
                        legalListName}, this.GetDMLegalListAdminOperationCompleted, userState);
        }
        
        private void OnGetDMLegalListAdminOperationCompleted(object arg) {
            if ((this.GetDMLegalListAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMLegalListAdminCompleted(this, new GetDMLegalListAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/GetDMLegalListLocalized" +
            "", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LegalListLocalized GetDMLegalListLocalized(string accesskey, string legalListName, string language) {
            object[] results = this.Invoke("GetDMLegalListLocalized", new object[] {
                        accesskey,
                        legalListName,
                        language});
            return ((LegalListLocalized)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMLegalListLocalizedAsync(string accesskey, string legalListName, string language) {
            this.GetDMLegalListLocalizedAsync(accesskey, legalListName, language, null);
        }
        
        /// <remarks/>
        public void GetDMLegalListLocalizedAsync(string accesskey, string legalListName, string language, object userState) {
            if ((this.GetDMLegalListLocalizedOperationCompleted == null)) {
                this.GetDMLegalListLocalizedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMLegalListLocalizedOperationCompleted);
            }
            this.InvokeAsync("GetDMLegalListLocalized", new object[] {
                        accesskey,
                        legalListName,
                        language}, this.GetDMLegalListLocalizedOperationCompleted, userState);
        }
        
        private void OnGetDMLegalListLocalizedOperationCompleted(object arg) {
            if ((this.GetDMLegalListLocalizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMLegalListLocalizedCompleted(this, new GetDMLegalListLocalizedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/GetDMLegalList", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LegalList GetDMLegalList(string accesskey, string legalListName) {
            object[] results = this.Invoke("GetDMLegalList", new object[] {
                        accesskey,
                        legalListName});
            return ((LegalList)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMLegalListAsync(string accesskey, string legalListName) {
            this.GetDMLegalListAsync(accesskey, legalListName, null);
        }
        
        /// <remarks/>
        public void GetDMLegalListAsync(string accesskey, string legalListName, object userState) {
            if ((this.GetDMLegalListOperationCompleted == null)) {
                this.GetDMLegalListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMLegalListOperationCompleted);
            }
            this.InvokeAsync("GetDMLegalList", new object[] {
                        accesskey,
                        legalListName}, this.GetDMLegalListOperationCompleted, userState);
        }
        
        private void OnGetDMLegalListOperationCompleted(object arg) {
            if ((this.GetDMLegalListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMLegalListCompleted(this, new GetDMLegalListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetUseSymbols", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetUseSymbols(string accesskey, string legalListName, bool enable) {
            this.Invoke("SetUseSymbols", new object[] {
                        accesskey,
                        legalListName,
                        enable});
        }
        
        /// <remarks/>
        public void SetUseSymbolsAsync(string accesskey, string legalListName, bool enable) {
            this.SetUseSymbolsAsync(accesskey, legalListName, enable, null);
        }
        
        /// <remarks/>
        public void SetUseSymbolsAsync(string accesskey, string legalListName, bool enable, object userState) {
            if ((this.SetUseSymbolsOperationCompleted == null)) {
                this.SetUseSymbolsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUseSymbolsOperationCompleted);
            }
            this.InvokeAsync("SetUseSymbols", new object[] {
                        accesskey,
                        legalListName,
                        enable}, this.SetUseSymbolsOperationCompleted, userState);
        }
        
        private void OnSetUseSymbolsOperationCompleted(object arg) {
            if ((this.SetUseSymbolsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUseSymbolsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetDefaultID", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetDefaultID(string accesskey, string legalListName, int defaultID) {
            this.Invoke("SetDefaultID", new object[] {
                        accesskey,
                        legalListName,
                        defaultID});
        }
        
        /// <remarks/>
        public void SetDefaultIDAsync(string accesskey, string legalListName, int defaultID) {
            this.SetDefaultIDAsync(accesskey, legalListName, defaultID, null);
        }
        
        /// <remarks/>
        public void SetDefaultIDAsync(string accesskey, string legalListName, int defaultID, object userState) {
            if ((this.SetDefaultIDOperationCompleted == null)) {
                this.SetDefaultIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDefaultIDOperationCompleted);
            }
            this.InvokeAsync("SetDefaultID", new object[] {
                        accesskey,
                        legalListName,
                        defaultID}, this.SetDefaultIDOperationCompleted, userState);
        }
        
        private void OnSetDefaultIDOperationCompleted(object arg) {
            if ((this.SetDefaultIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDefaultIDCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetLabel", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetLabel(string accesskey, string legalListName, string language, int entryID, string label, string owner) {
            this.Invoke("SetLabel", new object[] {
                        accesskey,
                        legalListName,
                        language,
                        entryID,
                        label,
                        owner});
        }
        
        /// <remarks/>
        public void SetLabelAsync(string accesskey, string legalListName, string language, int entryID, string label, string owner) {
            this.SetLabelAsync(accesskey, legalListName, language, entryID, label, owner, null);
        }
        
        /// <remarks/>
        public void SetLabelAsync(string accesskey, string legalListName, string language, int entryID, string label, string owner, object userState) {
            if ((this.SetLabelOperationCompleted == null)) {
                this.SetLabelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLabelOperationCompleted);
            }
            this.InvokeAsync("SetLabel", new object[] {
                        accesskey,
                        legalListName,
                        language,
                        entryID,
                        label,
                        owner}, this.SetLabelOperationCompleted, userState);
        }
        
        private void OnSetLabelOperationCompleted(object arg) {
            if ((this.SetLabelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLabelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/RemoveEntryForTenant", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveEntryForTenant(string accesskey, string legalListName, int entryID, string owner) {
            this.Invoke("RemoveEntryForTenant", new object[] {
                        accesskey,
                        legalListName,
                        entryID,
                        owner});
        }
        
        /// <remarks/>
        public void RemoveEntryForTenantAsync(string accesskey, string legalListName, int entryID, string owner) {
            this.RemoveEntryForTenantAsync(accesskey, legalListName, entryID, owner, null);
        }
        
        /// <remarks/>
        public void RemoveEntryForTenantAsync(string accesskey, string legalListName, int entryID, string owner, object userState) {
            if ((this.RemoveEntryForTenantOperationCompleted == null)) {
                this.RemoveEntryForTenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveEntryForTenantOperationCompleted);
            }
            this.InvokeAsync("RemoveEntryForTenant", new object[] {
                        accesskey,
                        legalListName,
                        entryID,
                        owner}, this.RemoveEntryForTenantOperationCompleted, userState);
        }
        
        private void OnRemoveEntryForTenantOperationCompleted(object arg) {
            if ((this.RemoveEntryForTenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveEntryForTenantCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetShortcut", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetShortcut(string accesskey, string legalListName, int entryID, string shortcut, string owner) {
            this.Invoke("SetShortcut", new object[] {
                        accesskey,
                        legalListName,
                        entryID,
                        shortcut,
                        owner});
        }
        
        /// <remarks/>
        public void SetShortcutAsync(string accesskey, string legalListName, int entryID, string shortcut, string owner) {
            this.SetShortcutAsync(accesskey, legalListName, entryID, shortcut, owner, null);
        }
        
        /// <remarks/>
        public void SetShortcutAsync(string accesskey, string legalListName, int entryID, string shortcut, string owner, object userState) {
            if ((this.SetShortcutOperationCompleted == null)) {
                this.SetShortcutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetShortcutOperationCompleted);
            }
            this.InvokeAsync("SetShortcut", new object[] {
                        accesskey,
                        legalListName,
                        entryID,
                        shortcut,
                        owner}, this.SetShortcutOperationCompleted, userState);
        }
        
        private void OnSetShortcutOperationCompleted(object arg) {
            if ((this.SetShortcutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetShortcutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetIcon", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetIcon(string accesskey, string legalListName, int entryID, string icon, string owner) {
            this.Invoke("SetIcon", new object[] {
                        accesskey,
                        legalListName,
                        entryID,
                        icon,
                        owner});
        }
        
        /// <remarks/>
        public void SetIconAsync(string accesskey, string legalListName, int entryID, string icon, string owner) {
            this.SetIconAsync(accesskey, legalListName, entryID, icon, owner, null);
        }
        
        /// <remarks/>
        public void SetIconAsync(string accesskey, string legalListName, int entryID, string icon, string owner, object userState) {
            if ((this.SetIconOperationCompleted == null)) {
                this.SetIconOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetIconOperationCompleted);
            }
            this.InvokeAsync("SetIcon", new object[] {
                        accesskey,
                        legalListName,
                        entryID,
                        icon,
                        owner}, this.SetIconOperationCompleted, userState);
        }
        
        private void OnSetIconOperationCompleted(object arg) {
            if ((this.SetIconCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetIconCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/AddEntry", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddEntry(string accesskey, string legalListName, int entryID) {
            object[] results = this.Invoke("AddEntry", new object[] {
                        accesskey,
                        legalListName,
                        entryID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddEntryAsync(string accesskey, string legalListName, int entryID) {
            this.AddEntryAsync(accesskey, legalListName, entryID, null);
        }
        
        /// <remarks/>
        public void AddEntryAsync(string accesskey, string legalListName, int entryID, object userState) {
            if ((this.AddEntryOperationCompleted == null)) {
                this.AddEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEntryOperationCompleted);
            }
            this.InvokeAsync("AddEntry", new object[] {
                        accesskey,
                        legalListName,
                        entryID}, this.AddEntryOperationCompleted, userState);
        }
        
        private void OnAddEntryOperationCompleted(object arg) {
            if ((this.AddEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEntryCompleted(this, new AddEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/RemoveEntry", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveEntry(string accesskey, string legalListName, int entryID) {
            this.Invoke("RemoveEntry", new object[] {
                        accesskey,
                        legalListName,
                        entryID});
        }
        
        /// <remarks/>
        public void RemoveEntryAsync(string accesskey, string legalListName, int entryID) {
            this.RemoveEntryAsync(accesskey, legalListName, entryID, null);
        }
        
        /// <remarks/>
        public void RemoveEntryAsync(string accesskey, string legalListName, int entryID, object userState) {
            if ((this.RemoveEntryOperationCompleted == null)) {
                this.RemoveEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveEntryOperationCompleted);
            }
            this.InvokeAsync("RemoveEntry", new object[] {
                        accesskey,
                        legalListName,
                        entryID}, this.RemoveEntryOperationCompleted, userState);
        }
        
        private void OnRemoveEntryOperationCompleted(object arg) {
            if ((this.RemoveEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveEntryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/LastModification", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LastModification(string accesskey, string legalListName) {
            object[] results = this.Invoke("LastModification", new object[] {
                        accesskey,
                        legalListName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LastModificationAsync(string accesskey, string legalListName) {
            this.LastModificationAsync(accesskey, legalListName, null);
        }
        
        /// <remarks/>
        public void LastModificationAsync(string accesskey, string legalListName, object userState) {
            if ((this.LastModificationOperationCompleted == null)) {
                this.LastModificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLastModificationOperationCompleted);
            }
            this.InvokeAsync("LastModification", new object[] {
                        accesskey,
                        legalListName}, this.LastModificationOperationCompleted, userState);
        }
        
        private void OnLastModificationOperationCompleted(object arg) {
            if ((this.LastModificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LastModificationCompleted(this, new LastModificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/GetCustomIndices", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomIndex[] GetCustomIndices(string accesskey, string legalListName) {
            object[] results = this.Invoke("GetCustomIndices", new object[] {
                        accesskey,
                        legalListName});
            return ((CustomIndex[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomIndicesAsync(string accesskey, string legalListName) {
            this.GetCustomIndicesAsync(accesskey, legalListName, null);
        }
        
        /// <remarks/>
        public void GetCustomIndicesAsync(string accesskey, string legalListName, object userState) {
            if ((this.GetCustomIndicesOperationCompleted == null)) {
                this.GetCustomIndicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomIndicesOperationCompleted);
            }
            this.InvokeAsync("GetCustomIndices", new object[] {
                        accesskey,
                        legalListName}, this.GetCustomIndicesOperationCompleted, userState);
        }
        
        private void OnGetCustomIndicesOperationCompleted(object arg) {
            if ((this.GetCustomIndicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomIndicesCompleted(this, new GetCustomIndicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmlegallistex2/SetCustomIndices", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetCustomIndices(string accesskey, string legalListName, CustomIndex[] indices) {
            this.Invoke("SetCustomIndices", new object[] {
                        accesskey,
                        legalListName,
                        indices});
        }
        
        /// <remarks/>
        public void SetCustomIndicesAsync(string accesskey, string legalListName, CustomIndex[] indices) {
            this.SetCustomIndicesAsync(accesskey, legalListName, indices, null);
        }
        
        /// <remarks/>
        public void SetCustomIndicesAsync(string accesskey, string legalListName, CustomIndex[] indices, object userState) {
            if ((this.SetCustomIndicesOperationCompleted == null)) {
                this.SetCustomIndicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCustomIndicesOperationCompleted);
            }
            this.InvokeAsync("SetCustomIndices", new object[] {
                        accesskey,
                        legalListName,
                        indices}, this.SetCustomIndicesOperationCompleted, userState);
        }
        
        private void OnSetCustomIndicesOperationCompleted(object arg) {
            if ((this.SetCustomIndicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCustomIndicesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListAdmin {
        
        private string legallistNameField;
        
        private int defaultIDField;
        
        private bool useSymbolsField;
        
        private string lastModificationField;
        
        private bool fixForPlatformField;
        
        private LegalListEntryAdmin[] entriesField;
        
        /// <remarks/>
        public string legallistName {
            get {
                return this.legallistNameField;
            }
            set {
                this.legallistNameField = value;
            }
        }
        
        /// <remarks/>
        public int defaultID {
            get {
                return this.defaultIDField;
            }
            set {
                this.defaultIDField = value;
            }
        }
        
        /// <remarks/>
        public bool useSymbols {
            get {
                return this.useSymbolsField;
            }
            set {
                this.useSymbolsField = value;
            }
        }
        
        /// <remarks/>
        public string lastModification {
            get {
                return this.lastModificationField;
            }
            set {
                this.lastModificationField = value;
            }
        }
        
        /// <remarks/>
        public bool fixForPlatform {
            get {
                return this.fixForPlatformField;
            }
            set {
                this.fixForPlatformField = value;
            }
        }
        
        /// <remarks/>
        public LegalListEntryAdmin[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListEntryAdmin {
        
        private int idField;
        
        private LegalListEntryTenantInfo[] tenantInfosField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public LegalListEntryTenantInfo[] tenantInfos {
            get {
                return this.tenantInfosField;
            }
            set {
                this.tenantInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListEntryTenantInfo {
        
        private string tenantField;
        
        private string iconField;
        
        private string shortcutField;
        
        private int customidxField;
        
        private LegalListLabel[] labelsField;
        
        /// <remarks/>
        public string tenant {
            get {
                return this.tenantField;
            }
            set {
                this.tenantField = value;
            }
        }
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string shortcut {
            get {
                return this.shortcutField;
            }
            set {
                this.shortcutField = value;
            }
        }
        
        /// <remarks/>
        public int customidx {
            get {
                return this.customidxField;
            }
            set {
                this.customidxField = value;
            }
        }
        
        /// <remarks/>
        public LegalListLabel[] labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListLabel {
        
        private string languageField;
        
        private string labelField;
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class CustomIndex {
        
        private int idField;
        
        private int customIndexField;
        
        private string ownerField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int customIndex {
            get {
                return this.customIndexField;
            }
            set {
                this.customIndexField = value;
            }
        }
        
        /// <remarks/>
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListEntry {
        
        private int idField;
        
        private string iconField;
        
        private string shortcutField;
        
        private int customidxField;
        
        private LegalListLabel[] labelsField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string shortcut {
            get {
                return this.shortcutField;
            }
            set {
                this.shortcutField = value;
            }
        }
        
        /// <remarks/>
        public int customidx {
            get {
                return this.customidxField;
            }
            set {
                this.customidxField = value;
            }
        }
        
        /// <remarks/>
        public LegalListLabel[] labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalList {
        
        private string legallistNameField;
        
        private int defaultIDField;
        
        private bool useSymbolsField;
        
        private string lastModificationField;
        
        private bool fixForPlatformField;
        
        private LegalListEntry[] entriesField;
        
        /// <remarks/>
        public string legallistName {
            get {
                return this.legallistNameField;
            }
            set {
                this.legallistNameField = value;
            }
        }
        
        /// <remarks/>
        public int defaultID {
            get {
                return this.defaultIDField;
            }
            set {
                this.defaultIDField = value;
            }
        }
        
        /// <remarks/>
        public bool useSymbols {
            get {
                return this.useSymbolsField;
            }
            set {
                this.useSymbolsField = value;
            }
        }
        
        /// <remarks/>
        public string lastModification {
            get {
                return this.lastModificationField;
            }
            set {
                this.lastModificationField = value;
            }
        }
        
        /// <remarks/>
        public bool fixForPlatform {
            get {
                return this.fixForPlatformField;
            }
            set {
                this.fixForPlatformField = value;
            }
        }
        
        /// <remarks/>
        public LegalListEntry[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListEntryLocalized {
        
        private int idField;
        
        private string iconField;
        
        private string shortcutField;
        
        private int customidxField;
        
        private string labelField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string shortcut {
            get {
                return this.shortcutField;
            }
            set {
                this.shortcutField = value;
            }
        }
        
        /// <remarks/>
        public int customidx {
            get {
                return this.customidxField;
            }
            set {
                this.customidxField = value;
            }
        }
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmlegallistex2")]
    public partial class LegalListLocalized {
        
        private string languageField;
        
        private string legallistNameField;
        
        private int defaultIDField;
        
        private bool useSymbolsField;
        
        private string lastModificationField;
        
        private bool fixForPlatformField;
        
        private LegalListEntryLocalized[] entriesField;
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string legallistName {
            get {
                return this.legallistNameField;
            }
            set {
                this.legallistNameField = value;
            }
        }
        
        /// <remarks/>
        public int defaultID {
            get {
                return this.defaultIDField;
            }
            set {
                this.defaultIDField = value;
            }
        }
        
        /// <remarks/>
        public bool useSymbols {
            get {
                return this.useSymbolsField;
            }
            set {
                this.useSymbolsField = value;
            }
        }
        
        /// <remarks/>
        public string lastModification {
            get {
                return this.lastModificationField;
            }
            set {
                this.lastModificationField = value;
            }
        }
        
        /// <remarks/>
        public bool fixForPlatform {
            get {
                return this.fixForPlatformField;
            }
            set {
                this.fixForPlatformField = value;
            }
        }
        
        /// <remarks/>
        public LegalListEntryLocalized[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetFixForPlatformCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllLegalListsCompletedEventHandler(object sender, GetAllLegalListsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllLegalListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllLegalListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LegalListAdmin[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LegalListAdmin[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMLegalListAdminCompletedEventHandler(object sender, GetDMLegalListAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMLegalListAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMLegalListAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LegalListAdmin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LegalListAdmin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMLegalListLocalizedCompletedEventHandler(object sender, GetDMLegalListLocalizedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMLegalListLocalizedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMLegalListLocalizedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LegalListLocalized Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LegalListLocalized)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMLegalListCompletedEventHandler(object sender, GetDMLegalListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMLegalListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMLegalListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LegalList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LegalList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetUseSymbolsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetDefaultIDCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetLabelCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RemoveEntryForTenantCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetShortcutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetIconCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddEntryCompletedEventHandler(object sender, AddEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RemoveEntryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LastModificationCompletedEventHandler(object sender, LastModificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LastModificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LastModificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCustomIndicesCompletedEventHandler(object sender, GetCustomIndicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomIndicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomIndicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomIndex[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomIndex[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetCustomIndicesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591