//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mamSearchAndRetrieval.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.5.20:12002/UserManagementWS/UM.asmx")]
        public string mamSearchAndRetrieval_org_ngs_ipmam_um_UM {
            get {
                return ((string)(this["mamSearchAndRetrieval_org_ngs_ipmam_um_UM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.5.20:12200/DataManagerWS/DMSearch.asmx")]
        public string mamSearchAndRetrieval_org_ngs_ipmam_dmSearch_DMSearch {
            get {
                return ((string)(this["mamSearchAndRetrieval_org_ngs_ipmam_dmSearch_DMSearch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.5.20:12200/DataManagerWS/DMEssencePackages.asmx")]
        public string mamSearchAndRetrieval_org_ngs_ipmam_dmEssencePackages_DMEssencePackages {
            get {
                return ((string)(this["mamSearchAndRetrieval_org_ngs_ipmam_dmEssencePackages_DMEssencePackages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.5.22:12300/EssenceManagerWS/EssenceManager.asmx")]
        public string mamSearchAndRetrieval_org_ngs_ipmam_essenceManager_EssenceManager {
            get {
                return ((string)(this["mamSearchAndRetrieval_org_ngs_ipmam_essenceManager_EssenceManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.5.20:12200/DataManagerWS/DMObjectAccess.asmx")]
        public string mamSearchAndRetrieval_org_ngs_ipmam_dmObjectAccess_DMObjectAccess {
            get {
                return ((string)(this["mamSearchAndRetrieval_org_ngs_ipmam_dmObjectAccess_DMObjectAccess"]));
            }
        }
    }
}
