//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace mamSearchAndRetrieval.org.ngs.ipmam.dmObjectAccess {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DMObjectAccessSoap", Namespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess")]
    public partial class DMObjectAccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateDMObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectExOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectExLocalizedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLegacyObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Test_GetDMObjectCompleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectAttributesByDMGUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectStrataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectStrataByDMGUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDMObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExistsDMObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDMObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMAttributesBulkOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMAttributeFlatOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDMAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddDMSegmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDMSegmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearDMStratumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMStrataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDMObjectClassesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccessAllowedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccessRightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccessRightsBulkOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DMObjectAccess() {
            this.Url = global::mamSearchAndRetrieval.Properties.Settings.Default.mamSearchAndRetrieval_org_ngs_ipmam_dmObjectAccess_DMObjectAccess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateDMObjectCompletedEventHandler CreateDMObjectCompleted;
        
        /// <remarks/>
        public event GetDMObjectExCompletedEventHandler GetDMObjectExCompleted;
        
        /// <remarks/>
        public event GetDMObjectExLocalizedCompletedEventHandler GetDMObjectExLocalizedCompleted;
        
        /// <remarks/>
        public event GetDMObjectCompletedEventHandler GetDMObjectCompleted;
        
        /// <remarks/>
        public event GetLegacyObjectCompletedEventHandler GetLegacyObjectCompleted;
        
        /// <remarks/>
        public event Test_GetDMObjectCompleteCompletedEventHandler Test_GetDMObjectCompleteCompleted;
        
        /// <remarks/>
        public event GetDMObjectAttributesCompletedEventHandler GetDMObjectAttributesCompleted;
        
        /// <remarks/>
        public event GetDMObjectAttributesByDMGUIDCompletedEventHandler GetDMObjectAttributesByDMGUIDCompleted;
        
        /// <remarks/>
        public event GetDMObjectStrataCompletedEventHandler GetDMObjectStrataCompleted;
        
        /// <remarks/>
        public event GetDMObjectStrataByDMGUIDCompletedEventHandler GetDMObjectStrataByDMGUIDCompleted;
        
        /// <remarks/>
        public event DeleteDMObjectCompletedEventHandler DeleteDMObjectCompleted;
        
        /// <remarks/>
        public event ExistsDMObjectCompletedEventHandler ExistsDMObjectCompleted;
        
        /// <remarks/>
        public event GetDMObjectClassCompletedEventHandler GetDMObjectClassCompleted;
        
        /// <remarks/>
        public event UpdateDMObjectCompletedEventHandler UpdateDMObjectCompleted;
        
        /// <remarks/>
        public event GetDMAttributeCompletedEventHandler GetDMAttributeCompleted;
        
        /// <remarks/>
        public event GetDMAttributesBulkCompletedEventHandler GetDMAttributesBulkCompleted;
        
        /// <remarks/>
        public event GetDMAttributeFlatCompletedEventHandler GetDMAttributeFlatCompleted;
        
        /// <remarks/>
        public event UpdateDMAttributeCompletedEventHandler UpdateDMAttributeCompleted;
        
        /// <remarks/>
        public event AddDMSegmentCompletedEventHandler AddDMSegmentCompleted;
        
        /// <remarks/>
        public event DeleteDMSegmentCompletedEventHandler DeleteDMSegmentCompleted;
        
        /// <remarks/>
        public event ClearDMStratumCompletedEventHandler ClearDMStratumCompleted;
        
        /// <remarks/>
        public event GetDMStrataCompletedEventHandler GetDMStrataCompleted;
        
        /// <remarks/>
        public event GetDMObjectClassesCompletedEventHandler GetDMObjectClassesCompleted;
        
        /// <remarks/>
        public event AccessAllowedCompletedEventHandler AccessAllowedCompleted;
        
        /// <remarks/>
        public event GetAccessRightsCompletedEventHandler GetAccessRightsCompleted;
        
        /// <remarks/>
        public event GetAccessRightsBulkCompletedEventHandler GetAccessRightsBulkCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/CreateDMObject", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDMObject(string axfdoc, string accesskey) {
            this.Invoke("CreateDMObject", new object[] {
                        axfdoc,
                        accesskey});
        }
        
        /// <remarks/>
        public void CreateDMObjectAsync(string axfdoc, string accesskey) {
            this.CreateDMObjectAsync(axfdoc, accesskey, null);
        }
        
        /// <remarks/>
        public void CreateDMObjectAsync(string axfdoc, string accesskey, object userState) {
            if ((this.CreateDMObjectOperationCompleted == null)) {
                this.CreateDMObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDMObjectOperationCompleted);
            }
            this.InvokeAsync("CreateDMObject", new object[] {
                        axfdoc,
                        accesskey}, this.CreateDMObjectOperationCompleted, userState);
        }
        
        private void OnCreateDMObjectOperationCompleted(object arg) {
            if ((this.CreateDMObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDMObjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectEx", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectEx(string axfdoc, string accesskey, bool includeAttributes, bool includeStrata, bool includeAssociations, bool includeEssencePackages) {
            object[] results = this.Invoke("GetDMObjectEx", new object[] {
                        axfdoc,
                        accesskey,
                        includeAttributes,
                        includeStrata,
                        includeAssociations,
                        includeEssencePackages});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectExAsync(string axfdoc, string accesskey, bool includeAttributes, bool includeStrata, bool includeAssociations, bool includeEssencePackages) {
            this.GetDMObjectExAsync(axfdoc, accesskey, includeAttributes, includeStrata, includeAssociations, includeEssencePackages, null);
        }
        
        /// <remarks/>
        public void GetDMObjectExAsync(string axfdoc, string accesskey, bool includeAttributes, bool includeStrata, bool includeAssociations, bool includeEssencePackages, object userState) {
            if ((this.GetDMObjectExOperationCompleted == null)) {
                this.GetDMObjectExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectExOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectEx", new object[] {
                        axfdoc,
                        accesskey,
                        includeAttributes,
                        includeStrata,
                        includeAssociations,
                        includeEssencePackages}, this.GetDMObjectExOperationCompleted, userState);
        }
        
        private void OnGetDMObjectExOperationCompleted(object arg) {
            if ((this.GetDMObjectExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectExCompleted(this, new GetDMObjectExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectExLocalized", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectExLocalized(string axfdoc, string accesskey, bool includeAttributes, bool includeStrata, bool includeAssociations, bool includeEssencePackages, string language, string framerate) {
            object[] results = this.Invoke("GetDMObjectExLocalized", new object[] {
                        axfdoc,
                        accesskey,
                        includeAttributes,
                        includeStrata,
                        includeAssociations,
                        includeEssencePackages,
                        language,
                        framerate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectExLocalizedAsync(string axfdoc, string accesskey, bool includeAttributes, bool includeStrata, bool includeAssociations, bool includeEssencePackages, string language, string framerate) {
            this.GetDMObjectExLocalizedAsync(axfdoc, accesskey, includeAttributes, includeStrata, includeAssociations, includeEssencePackages, language, framerate, null);
        }
        
        /// <remarks/>
        public void GetDMObjectExLocalizedAsync(string axfdoc, string accesskey, bool includeAttributes, bool includeStrata, bool includeAssociations, bool includeEssencePackages, string language, string framerate, object userState) {
            if ((this.GetDMObjectExLocalizedOperationCompleted == null)) {
                this.GetDMObjectExLocalizedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectExLocalizedOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectExLocalized", new object[] {
                        axfdoc,
                        accesskey,
                        includeAttributes,
                        includeStrata,
                        includeAssociations,
                        includeEssencePackages,
                        language,
                        framerate}, this.GetDMObjectExLocalizedOperationCompleted, userState);
        }
        
        private void OnGetDMObjectExLocalizedOperationCompleted(object arg) {
            if ((this.GetDMObjectExLocalizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectExLocalizedCompleted(this, new GetDMObjectExLocalizedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObject", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObject(string axfdoc, string accesskey) {
            object[] results = this.Invoke("GetDMObject", new object[] {
                        axfdoc,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectAsync(string axfdoc, string accesskey) {
            this.GetDMObjectAsync(axfdoc, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectAsync(string axfdoc, string accesskey, object userState) {
            if ((this.GetDMObjectOperationCompleted == null)) {
                this.GetDMObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectOperationCompleted);
            }
            this.InvokeAsync("GetDMObject", new object[] {
                        axfdoc,
                        accesskey}, this.GetDMObjectOperationCompleted, userState);
        }
        
        private void OnGetDMObjectOperationCompleted(object arg) {
            if ((this.GetDMObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectCompleted(this, new GetDMObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetLegacyObject", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLegacyObject(string dmguid, string datamanager, string accesskey) {
            object[] results = this.Invoke("GetLegacyObject", new object[] {
                        dmguid,
                        datamanager,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLegacyObjectAsync(string dmguid, string datamanager, string accesskey) {
            this.GetLegacyObjectAsync(dmguid, datamanager, accesskey, null);
        }
        
        /// <remarks/>
        public void GetLegacyObjectAsync(string dmguid, string datamanager, string accesskey, object userState) {
            if ((this.GetLegacyObjectOperationCompleted == null)) {
                this.GetLegacyObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLegacyObjectOperationCompleted);
            }
            this.InvokeAsync("GetLegacyObject", new object[] {
                        dmguid,
                        datamanager,
                        accesskey}, this.GetLegacyObjectOperationCompleted, userState);
        }
        
        private void OnGetLegacyObjectOperationCompleted(object arg) {
            if ((this.GetLegacyObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLegacyObjectCompleted(this, new GetLegacyObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/Test_GetDMObjectComplet" +
            "e", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Test_GetDMObjectComplete(string accessKey, string mdclass, string guid) {
            object[] results = this.Invoke("Test_GetDMObjectComplete", new object[] {
                        accessKey,
                        mdclass,
                        guid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void Test_GetDMObjectCompleteAsync(string accessKey, string mdclass, string guid) {
            this.Test_GetDMObjectCompleteAsync(accessKey, mdclass, guid, null);
        }
        
        /// <remarks/>
        public void Test_GetDMObjectCompleteAsync(string accessKey, string mdclass, string guid, object userState) {
            if ((this.Test_GetDMObjectCompleteOperationCompleted == null)) {
                this.Test_GetDMObjectCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTest_GetDMObjectCompleteOperationCompleted);
            }
            this.InvokeAsync("Test_GetDMObjectComplete", new object[] {
                        accessKey,
                        mdclass,
                        guid}, this.Test_GetDMObjectCompleteOperationCompleted, userState);
        }
        
        private void OnTest_GetDMObjectCompleteOperationCompleted(object arg) {
            if ((this.Test_GetDMObjectCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Test_GetDMObjectCompleteCompleted(this, new Test_GetDMObjectCompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectAttributes", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectAttributes(string axfdoc, string accesskey) {
            object[] results = this.Invoke("GetDMObjectAttributes", new object[] {
                        axfdoc,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectAttributesAsync(string axfdoc, string accesskey) {
            this.GetDMObjectAttributesAsync(axfdoc, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectAttributesAsync(string axfdoc, string accesskey, object userState) {
            if ((this.GetDMObjectAttributesOperationCompleted == null)) {
                this.GetDMObjectAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectAttributesOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectAttributes", new object[] {
                        axfdoc,
                        accesskey}, this.GetDMObjectAttributesOperationCompleted, userState);
        }
        
        private void OnGetDMObjectAttributesOperationCompleted(object arg) {
            if ((this.GetDMObjectAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectAttributesCompleted(this, new GetDMObjectAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectAttributesBy" +
            "DMGUID", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectAttributesByDMGUID(string dmguid, string accesskey) {
            object[] results = this.Invoke("GetDMObjectAttributesByDMGUID", new object[] {
                        dmguid,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectAttributesByDMGUIDAsync(string dmguid, string accesskey) {
            this.GetDMObjectAttributesByDMGUIDAsync(dmguid, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectAttributesByDMGUIDAsync(string dmguid, string accesskey, object userState) {
            if ((this.GetDMObjectAttributesByDMGUIDOperationCompleted == null)) {
                this.GetDMObjectAttributesByDMGUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectAttributesByDMGUIDOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectAttributesByDMGUID", new object[] {
                        dmguid,
                        accesskey}, this.GetDMObjectAttributesByDMGUIDOperationCompleted, userState);
        }
        
        private void OnGetDMObjectAttributesByDMGUIDOperationCompleted(object arg) {
            if ((this.GetDMObjectAttributesByDMGUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectAttributesByDMGUIDCompleted(this, new GetDMObjectAttributesByDMGUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectStrata", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectStrata(string axfdoc, string accesskey) {
            object[] results = this.Invoke("GetDMObjectStrata", new object[] {
                        axfdoc,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectStrataAsync(string axfdoc, string accesskey) {
            this.GetDMObjectStrataAsync(axfdoc, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectStrataAsync(string axfdoc, string accesskey, object userState) {
            if ((this.GetDMObjectStrataOperationCompleted == null)) {
                this.GetDMObjectStrataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectStrataOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectStrata", new object[] {
                        axfdoc,
                        accesskey}, this.GetDMObjectStrataOperationCompleted, userState);
        }
        
        private void OnGetDMObjectStrataOperationCompleted(object arg) {
            if ((this.GetDMObjectStrataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectStrataCompleted(this, new GetDMObjectStrataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectStrataByDMGU" +
            "ID", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectStrataByDMGUID(string dmguid, string accesskey) {
            object[] results = this.Invoke("GetDMObjectStrataByDMGUID", new object[] {
                        dmguid,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectStrataByDMGUIDAsync(string dmguid, string accesskey) {
            this.GetDMObjectStrataByDMGUIDAsync(dmguid, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectStrataByDMGUIDAsync(string dmguid, string accesskey, object userState) {
            if ((this.GetDMObjectStrataByDMGUIDOperationCompleted == null)) {
                this.GetDMObjectStrataByDMGUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectStrataByDMGUIDOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectStrataByDMGUID", new object[] {
                        dmguid,
                        accesskey}, this.GetDMObjectStrataByDMGUIDOperationCompleted, userState);
        }
        
        private void OnGetDMObjectStrataByDMGUIDOperationCompleted(object arg) {
            if ((this.GetDMObjectStrataByDMGUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectStrataByDMGUIDCompleted(this, new GetDMObjectStrataByDMGUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/DeleteDMObject", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteDMObject(string DMGUID, string accesskey) {
            this.Invoke("DeleteDMObject", new object[] {
                        DMGUID,
                        accesskey});
        }
        
        /// <remarks/>
        public void DeleteDMObjectAsync(string DMGUID, string accesskey) {
            this.DeleteDMObjectAsync(DMGUID, accesskey, null);
        }
        
        /// <remarks/>
        public void DeleteDMObjectAsync(string DMGUID, string accesskey, object userState) {
            if ((this.DeleteDMObjectOperationCompleted == null)) {
                this.DeleteDMObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDMObjectOperationCompleted);
            }
            this.InvokeAsync("DeleteDMObject", new object[] {
                        DMGUID,
                        accesskey}, this.DeleteDMObjectOperationCompleted, userState);
        }
        
        private void OnDeleteDMObjectOperationCompleted(object arg) {
            if ((this.DeleteDMObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDMObjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/ExistsDMObject", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExistsDMObject(string dmguid, string mdclass, string accesskey) {
            object[] results = this.Invoke("ExistsDMObject", new object[] {
                        dmguid,
                        mdclass,
                        accesskey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsDMObjectAsync(string dmguid, string mdclass, string accesskey) {
            this.ExistsDMObjectAsync(dmguid, mdclass, accesskey, null);
        }
        
        /// <remarks/>
        public void ExistsDMObjectAsync(string dmguid, string mdclass, string accesskey, object userState) {
            if ((this.ExistsDMObjectOperationCompleted == null)) {
                this.ExistsDMObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsDMObjectOperationCompleted);
            }
            this.InvokeAsync("ExistsDMObject", new object[] {
                        dmguid,
                        mdclass,
                        accesskey}, this.ExistsDMObjectOperationCompleted, userState);
        }
        
        private void OnExistsDMObjectOperationCompleted(object arg) {
            if ((this.ExistsDMObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsDMObjectCompleted(this, new ExistsDMObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectClass", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMObjectClass(string dmguid, string accesskey) {
            object[] results = this.Invoke("GetDMObjectClass", new object[] {
                        dmguid,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectClassAsync(string dmguid, string accesskey) {
            this.GetDMObjectClassAsync(dmguid, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectClassAsync(string dmguid, string accesskey, object userState) {
            if ((this.GetDMObjectClassOperationCompleted == null)) {
                this.GetDMObjectClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectClassOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectClass", new object[] {
                        dmguid,
                        accesskey}, this.GetDMObjectClassOperationCompleted, userState);
        }
        
        private void OnGetDMObjectClassOperationCompleted(object arg) {
            if ((this.GetDMObjectClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectClassCompleted(this, new GetDMObjectClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/UpdateDMObject", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateDMObject(string axf, string accesskey) {
            this.Invoke("UpdateDMObject", new object[] {
                        axf,
                        accesskey});
        }
        
        /// <remarks/>
        public void UpdateDMObjectAsync(string axf, string accesskey) {
            this.UpdateDMObjectAsync(axf, accesskey, null);
        }
        
        /// <remarks/>
        public void UpdateDMObjectAsync(string axf, string accesskey, object userState) {
            if ((this.UpdateDMObjectOperationCompleted == null)) {
                this.UpdateDMObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDMObjectOperationCompleted);
            }
            this.InvokeAsync("UpdateDMObject", new object[] {
                        axf,
                        accesskey}, this.UpdateDMObjectOperationCompleted, userState);
        }
        
        private void OnUpdateDMObjectOperationCompleted(object arg) {
            if ((this.UpdateDMObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDMObjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMAttribute", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMAttribute(string dmguid, string attribute, string accesskey) {
            object[] results = this.Invoke("GetDMAttribute", new object[] {
                        dmguid,
                        attribute,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMAttributeAsync(string dmguid, string attribute, string accesskey) {
            this.GetDMAttributeAsync(dmguid, attribute, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMAttributeAsync(string dmguid, string attribute, string accesskey, object userState) {
            if ((this.GetDMAttributeOperationCompleted == null)) {
                this.GetDMAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMAttributeOperationCompleted);
            }
            this.InvokeAsync("GetDMAttribute", new object[] {
                        dmguid,
                        attribute,
                        accesskey}, this.GetDMAttributeOperationCompleted, userState);
        }
        
        private void OnGetDMAttributeOperationCompleted(object arg) {
            if ((this.GetDMAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMAttributeCompleted(this, new GetDMAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMAttributesBulk", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AttributeValues[] GetDMAttributesBulk(string[] dmguids, string[] attributes, string accesskey) {
            object[] results = this.Invoke("GetDMAttributesBulk", new object[] {
                        dmguids,
                        attributes,
                        accesskey});
            return ((AttributeValues[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDMAttributesBulkAsync(string[] dmguids, string[] attributes, string accesskey) {
            this.GetDMAttributesBulkAsync(dmguids, attributes, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMAttributesBulkAsync(string[] dmguids, string[] attributes, string accesskey, object userState) {
            if ((this.GetDMAttributesBulkOperationCompleted == null)) {
                this.GetDMAttributesBulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMAttributesBulkOperationCompleted);
            }
            this.InvokeAsync("GetDMAttributesBulk", new object[] {
                        dmguids,
                        attributes,
                        accesskey}, this.GetDMAttributesBulkOperationCompleted, userState);
        }
        
        private void OnGetDMAttributesBulkOperationCompleted(object arg) {
            if ((this.GetDMAttributesBulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMAttributesBulkCompleted(this, new GetDMAttributesBulkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMAttributeFlat", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDMAttributeFlat(string dmguid, string attribute, string accesskey) {
            object[] results = this.Invoke("GetDMAttributeFlat", new object[] {
                        dmguid,
                        attribute,
                        accesskey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDMAttributeFlatAsync(string dmguid, string attribute, string accesskey) {
            this.GetDMAttributeFlatAsync(dmguid, attribute, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMAttributeFlatAsync(string dmguid, string attribute, string accesskey, object userState) {
            if ((this.GetDMAttributeFlatOperationCompleted == null)) {
                this.GetDMAttributeFlatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMAttributeFlatOperationCompleted);
            }
            this.InvokeAsync("GetDMAttributeFlat", new object[] {
                        dmguid,
                        attribute,
                        accesskey}, this.GetDMAttributeFlatOperationCompleted, userState);
        }
        
        private void OnGetDMAttributeFlatOperationCompleted(object arg) {
            if ((this.GetDMAttributeFlatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMAttributeFlatCompleted(this, new GetDMAttributeFlatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/UpdateDMAttribute", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateDMAttribute(string dmguid, string attribute, string value, string accesskey) {
            this.Invoke("UpdateDMAttribute", new object[] {
                        dmguid,
                        attribute,
                        value,
                        accesskey});
        }
        
        /// <remarks/>
        public void UpdateDMAttributeAsync(string dmguid, string attribute, string value, string accesskey) {
            this.UpdateDMAttributeAsync(dmguid, attribute, value, accesskey, null);
        }
        
        /// <remarks/>
        public void UpdateDMAttributeAsync(string dmguid, string attribute, string value, string accesskey, object userState) {
            if ((this.UpdateDMAttributeOperationCompleted == null)) {
                this.UpdateDMAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDMAttributeOperationCompleted);
            }
            this.InvokeAsync("UpdateDMAttribute", new object[] {
                        dmguid,
                        attribute,
                        value,
                        accesskey}, this.UpdateDMAttributeOperationCompleted, userState);
        }
        
        private void OnUpdateDMAttributeOperationCompleted(object arg) {
            if ((this.UpdateDMAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDMAttributeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/AddDMSegment", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddDMSegment(string dmguid, string stratum, int startTC, int stopTC, string content, string accesskey) {
            this.Invoke("AddDMSegment", new object[] {
                        dmguid,
                        stratum,
                        startTC,
                        stopTC,
                        content,
                        accesskey});
        }
        
        /// <remarks/>
        public void AddDMSegmentAsync(string dmguid, string stratum, int startTC, int stopTC, string content, string accesskey) {
            this.AddDMSegmentAsync(dmguid, stratum, startTC, stopTC, content, accesskey, null);
        }
        
        /// <remarks/>
        public void AddDMSegmentAsync(string dmguid, string stratum, int startTC, int stopTC, string content, string accesskey, object userState) {
            if ((this.AddDMSegmentOperationCompleted == null)) {
                this.AddDMSegmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDMSegmentOperationCompleted);
            }
            this.InvokeAsync("AddDMSegment", new object[] {
                        dmguid,
                        stratum,
                        startTC,
                        stopTC,
                        content,
                        accesskey}, this.AddDMSegmentOperationCompleted, userState);
        }
        
        private void OnAddDMSegmentOperationCompleted(object arg) {
            if ((this.AddDMSegmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDMSegmentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/DeleteDMSegment", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteDMSegment(string dmguid, string stratum, int startTC, string accesskey) {
            this.Invoke("DeleteDMSegment", new object[] {
                        dmguid,
                        stratum,
                        startTC,
                        accesskey});
        }
        
        /// <remarks/>
        public void DeleteDMSegmentAsync(string dmguid, string stratum, int startTC, string accesskey) {
            this.DeleteDMSegmentAsync(dmguid, stratum, startTC, accesskey, null);
        }
        
        /// <remarks/>
        public void DeleteDMSegmentAsync(string dmguid, string stratum, int startTC, string accesskey, object userState) {
            if ((this.DeleteDMSegmentOperationCompleted == null)) {
                this.DeleteDMSegmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDMSegmentOperationCompleted);
            }
            this.InvokeAsync("DeleteDMSegment", new object[] {
                        dmguid,
                        stratum,
                        startTC,
                        accesskey}, this.DeleteDMSegmentOperationCompleted, userState);
        }
        
        private void OnDeleteDMSegmentOperationCompleted(object arg) {
            if ((this.DeleteDMSegmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDMSegmentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/ClearDMStratum", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearDMStratum(string dmguid, string stratum, string accesskey) {
            this.Invoke("ClearDMStratum", new object[] {
                        dmguid,
                        stratum,
                        accesskey});
        }
        
        /// <remarks/>
        public void ClearDMStratumAsync(string dmguid, string stratum, string accesskey) {
            this.ClearDMStratumAsync(dmguid, stratum, accesskey, null);
        }
        
        /// <remarks/>
        public void ClearDMStratumAsync(string dmguid, string stratum, string accesskey, object userState) {
            if ((this.ClearDMStratumOperationCompleted == null)) {
                this.ClearDMStratumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearDMStratumOperationCompleted);
            }
            this.InvokeAsync("ClearDMStratum", new object[] {
                        dmguid,
                        stratum,
                        accesskey}, this.ClearDMStratumOperationCompleted, userState);
        }
        
        private void OnClearDMStratumOperationCompleted(object arg) {
            if ((this.ClearDMStratumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearDMStratumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMStrata", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetDMStrata(string mdclass, string accesskey) {
            object[] results = this.Invoke("GetDMStrata", new object[] {
                        mdclass,
                        accesskey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDMStrataAsync(string mdclass, string accesskey) {
            this.GetDMStrataAsync(mdclass, accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMStrataAsync(string mdclass, string accesskey, object userState) {
            if ((this.GetDMStrataOperationCompleted == null)) {
                this.GetDMStrataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMStrataOperationCompleted);
            }
            this.InvokeAsync("GetDMStrata", new object[] {
                        mdclass,
                        accesskey}, this.GetDMStrataOperationCompleted, userState);
        }
        
        private void OnGetDMStrataOperationCompleted(object arg) {
            if ((this.GetDMStrataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMStrataCompleted(this, new GetDMStrataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetDMObjectClasses", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetDMObjectClasses(string accesskey) {
            object[] results = this.Invoke("GetDMObjectClasses", new object[] {
                        accesskey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDMObjectClassesAsync(string accesskey) {
            this.GetDMObjectClassesAsync(accesskey, null);
        }
        
        /// <remarks/>
        public void GetDMObjectClassesAsync(string accesskey, object userState) {
            if ((this.GetDMObjectClassesOperationCompleted == null)) {
                this.GetDMObjectClassesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDMObjectClassesOperationCompleted);
            }
            this.InvokeAsync("GetDMObjectClasses", new object[] {
                        accesskey}, this.GetDMObjectClassesOperationCompleted, userState);
        }
        
        private void OnGetDMObjectClassesOperationCompleted(object arg) {
            if ((this.GetDMObjectClassesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDMObjectClassesCompleted(this, new GetDMObjectClassesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/AccessAllowed", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AccessAllowed(string dmguid, string accesskey) {
            object[] results = this.Invoke("AccessAllowed", new object[] {
                        dmguid,
                        accesskey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AccessAllowedAsync(string dmguid, string accesskey) {
            this.AccessAllowedAsync(dmguid, accesskey, null);
        }
        
        /// <remarks/>
        public void AccessAllowedAsync(string dmguid, string accesskey, object userState) {
            if ((this.AccessAllowedOperationCompleted == null)) {
                this.AccessAllowedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccessAllowedOperationCompleted);
            }
            this.InvokeAsync("AccessAllowed", new object[] {
                        dmguid,
                        accesskey}, this.AccessAllowedOperationCompleted, userState);
        }
        
        private void OnAccessAllowedOperationCompleted(object arg) {
            if ((this.AccessAllowedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccessAllowedCompleted(this, new AccessAllowedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetAccessRights", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ulong GetAccessRights(string dmguid, ulong rightsToCheck, string accesskey) {
            object[] results = this.Invoke("GetAccessRights", new object[] {
                        dmguid,
                        rightsToCheck,
                        accesskey});
            return ((ulong)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccessRightsAsync(string dmguid, ulong rightsToCheck, string accesskey) {
            this.GetAccessRightsAsync(dmguid, rightsToCheck, accesskey, null);
        }
        
        /// <remarks/>
        public void GetAccessRightsAsync(string dmguid, ulong rightsToCheck, string accesskey, object userState) {
            if ((this.GetAccessRightsOperationCompleted == null)) {
                this.GetAccessRightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccessRightsOperationCompleted);
            }
            this.InvokeAsync("GetAccessRights", new object[] {
                        dmguid,
                        rightsToCheck,
                        accesskey}, this.GetAccessRightsOperationCompleted, userState);
        }
        
        private void OnGetAccessRightsOperationCompleted(object arg) {
            if ((this.GetAccessRightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccessRightsCompleted(this, new GetAccessRightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blue-order.com/ma/datamanagerws/dmobjectaccess/GetAccessRightsBulk", RequestNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", ResponseNamespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ulong[] GetAccessRightsBulk(string[] dmguids, ulong rightsToCheck, string accesskey) {
            object[] results = this.Invoke("GetAccessRightsBulk", new object[] {
                        dmguids,
                        rightsToCheck,
                        accesskey});
            return ((ulong[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccessRightsBulkAsync(string[] dmguids, ulong rightsToCheck, string accesskey) {
            this.GetAccessRightsBulkAsync(dmguids, rightsToCheck, accesskey, null);
        }
        
        /// <remarks/>
        public void GetAccessRightsBulkAsync(string[] dmguids, ulong rightsToCheck, string accesskey, object userState) {
            if ((this.GetAccessRightsBulkOperationCompleted == null)) {
                this.GetAccessRightsBulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccessRightsBulkOperationCompleted);
            }
            this.InvokeAsync("GetAccessRightsBulk", new object[] {
                        dmguids,
                        rightsToCheck,
                        accesskey}, this.GetAccessRightsBulkOperationCompleted, userState);
        }
        
        private void OnGetAccessRightsBulkOperationCompleted(object arg) {
            if ((this.GetAccessRightsBulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccessRightsBulkCompleted(this, new GetAccessRightsBulkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blue-order.com/ma/datamanagerws/dmobjectaccess")]
    public partial class AttributeValues {
        
        private string[] valuesField;
        
        /// <remarks/>
        public string[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateDMObjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectExCompletedEventHandler(object sender, GetDMObjectExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectExLocalizedCompletedEventHandler(object sender, GetDMObjectExLocalizedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectExLocalizedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectExLocalizedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectCompletedEventHandler(object sender, GetDMObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetLegacyObjectCompletedEventHandler(object sender, GetLegacyObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLegacyObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLegacyObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Test_GetDMObjectCompleteCompletedEventHandler(object sender, Test_GetDMObjectCompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Test_GetDMObjectCompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Test_GetDMObjectCompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectAttributesCompletedEventHandler(object sender, GetDMObjectAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectAttributesByDMGUIDCompletedEventHandler(object sender, GetDMObjectAttributesByDMGUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectAttributesByDMGUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectAttributesByDMGUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectStrataCompletedEventHandler(object sender, GetDMObjectStrataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectStrataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectStrataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectStrataByDMGUIDCompletedEventHandler(object sender, GetDMObjectStrataByDMGUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectStrataByDMGUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectStrataByDMGUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteDMObjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ExistsDMObjectCompletedEventHandler(object sender, ExistsDMObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsDMObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsDMObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectClassCompletedEventHandler(object sender, GetDMObjectClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateDMObjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMAttributeCompletedEventHandler(object sender, GetDMAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMAttributesBulkCompletedEventHandler(object sender, GetDMAttributesBulkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMAttributesBulkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMAttributesBulkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AttributeValues[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AttributeValues[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMAttributeFlatCompletedEventHandler(object sender, GetDMAttributeFlatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMAttributeFlatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMAttributeFlatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateDMAttributeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddDMSegmentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteDMSegmentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ClearDMStratumCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMStrataCompletedEventHandler(object sender, GetDMStrataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMStrataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMStrataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDMObjectClassesCompletedEventHandler(object sender, GetDMObjectClassesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDMObjectClassesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDMObjectClassesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AccessAllowedCompletedEventHandler(object sender, AccessAllowedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccessAllowedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccessAllowedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAccessRightsCompletedEventHandler(object sender, GetAccessRightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccessRightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccessRightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ulong Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ulong)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAccessRightsBulkCompletedEventHandler(object sender, GetAccessRightsBulkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccessRightsBulkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccessRightsBulkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ulong[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ulong[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591